language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

git:
  depth: 5

env:
  global:
    - SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1
    - RUN_PHPSTAN=0

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: bionic
      env:
        - RUN_PHPSTAN=1
    - php: nightly
      dist: bionic
  fast_finish: true

install: |
    if [[ $RUN_PHPSTAN = '0' ]]; then
      composer remove phpstan/phpstan --dev --no-update
    fi
    if [[ $TRAVIS_PHP_VERSION = "7.4" ]]; then
      export SYMFONY_PHPUNIT_VERSION=7.5
    fi
    if [[ $TRAVIS_PHP_VERSION = nightly ]]; then
      export SYMFONY_PHPUNIT_VERSION=9.4
      # install the phpunit-bridge with PHP 7.4 when testing nightly
      (cd / && wget https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/18.04/x86_64/php-7.4.tar.bz2 -O - | tar -xj)
      phpenv global 7.4
      composer update --no-interaction --no-progress --prefer-dist --ansi
      vendor/bin/simple-phpunit install
      phpenv global nightly
    else
      composer update --no-interaction --no-progress --prefer-dist --ansi
    fi
    composer show

script:
  - vendor/bin/simple-phpunit
  - if [[ $RUN_PHPSTAN = '1' ]]; then composer require phpunit/phpunit:^7.5 --dev; vendor/bin/phpstan analyse; fi
