language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

git:
  depth: 5
  
env:
  - REMOVE_PHPSTAN: 1

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      env:
        - REMOVE_PHPSTAN=0
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - if [[ $REMOVE_PHPSTAN = '1' ]]; then composer remove phpstan/phpstan --no-update; fi
  - composer update --no-interaction --no-progress --prefer-dist --ansi

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - if [[ $REMOVE_PHPSTAN = '0' ]]; then vendor/bin/phpstan analyse; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
